[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "cancun"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
opbnb_testnet = "https://opbnb-testnet-rpc.bnbchain.org"
opbnb_mainnet = "https://opbnb-mainnet-rpc.bnbchain.org"
bsc_testnet   = "https://data-seed-prebsc-1-s1.binance.org:8545"
bsc_mainnet   = "https://bsc-dataseed.binance.org"

[etherscan]
opbnb_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-opbnb-testnet.bscscan.com/api" }
opbnb_mainnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-opbnb.bscscan.com/api" }
bsc_testnet   = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
bsc_mainnet   = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
